export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header 
        style={{
          backgroundColor:"lightblue",
          padding:"1rem"
        }}
        >
          <h4>Header</h4>
        </header>
        {children}
        <footer 
        style={{
          backgroundColor:'lime',
          padding:"1rem"
        }}
        >
          <h4>Footer</h4>
        </footer>
      </body>
    </html>
  )
}
